name: Publish Package to NPM

on:
  push:
    branches:
      - "main"
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Extract version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG=v$VERSION" >> $GITHUB_OUTPUT

      - name: List files to be published
        run: npm pack --dry-run

      - name: Publish to NPM
        run: |
          npm publish || echo "Package version may already exist, continuing workflow"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Create and push tag
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     # Check if tag exists locally before trying to delete it
      #     if git tag | grep -q "^${{ steps.get_version.outputs.TAG }}$"; then
      #       git tag -d ${{ steps.get_version.outputs.TAG }}
      #     fi
      #     git tag -a ${{ steps.get_version.outputs.TAG }} -m "Release ${{ steps.get_version.outputs.VERSION }}"
      #     git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ steps.get_version.outputs.TAG }} --force

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.get_version.outputs.TAG }}
      #     generate_release_notes: true
